version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - "janthijs"
    allow:
      - dependency-type: "direct"
