version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "master"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - "jasperswart"
      - "janthijs"
    allow:
      - dependency-type: "direct"
