version: "3.5"
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    ipc: host
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-subsidieregister}:${VERSION:-latest}

  dev:
    build:
      context: .
    ports:
      - "8080:80"
    ipc: host
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-subsidieregister}-dev:${VERSION:-latest}

  unittest:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=test
      - CI=true
      - TZ=Europe/Amsterdam
      - BUILD_ARG=acc
    command: npm run test
